alias r='rails'
alias rt='rails test'
alias rts='rails test test/system'
alias rs='rails server'
alias rc='rails console'
alias rdb='rails dbconsole'

alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
