#!/usr/bin/env bash

# Copyright (c) <Matt Stauffer>

## Error handling
abort()
{
    echo >&2 '
***********************************************
*** There was an error running this script. ***
***********************************************
'
    echo "An error occurred. Exiting..." >&2
    exit 1
}

trap 'abort' 0

set -e
## Start script
cd $PROJECTS_RAILS
PROJECTNAME=$1
rails new $PROJECTNAME
cd $PROJECTNAME
git init
git add .
git commit -m "Initial commit."
# open "http://$PROJECTNAME.dev"
echo "***********************"
echo "You're ready to go!"

# End script; disable error handling
trap : 0
